name: spatial-fs-benchmark
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - r-base=4.5
  - gxx_linux-64
  - bioconductor-batchelor
  - bioconductor-biobase
  - bioconductor-biocneighbors
  - bioconductor-biocstyle
  - bioconductor-bluster
  - bioconductor-clusterprofiler
  - bioconductor-edger
  - bioconductor-enrichplot
  - bioconductor-go.db
  - bioconductor-m3drop
  - bioconductor-org.hs.eg.db
  - bioconductor-org.mm.eg.db
  - bioconductor-scater
  - bioconductor-scmerge
  - bioconductor-scran
  - bioconductor-scry
  - bioconductor-scuttle
  - bioconductor-singlecellexperiment
  - bioconductor-summarizedexperiment
  - bioconductor-zellkonverter
  - r-data.table
  - r-docopt
  - r-readr
  - r-dplyr
  - r-tidyr
  - r-ggplot2
  - r-ggwordcloud
  - r-patchwork
  - r-rcolorbrewer
  - r-fs
  - r-gridextra
  - r-igraph
  - r-irlba
  - r-kml
  - r-leiden
  - r-magrittr
  - r-matrix
  - r-matrixcalc
  - r-multimode
  - r-qlcmatrix
  - r-rcpp
  - r-rcppeigen
  - r-remotes
  - r-reticulate
  - r-rtsne
  - r-sctransform
  - r-seurat
  - r-seuratobject
  - r-signal
  - r-tibble
  - r-tidytext
  - r-umap
  - r-uwot
  - pip:
      - anticor_features==0.1.8
      - gprofiler-official==0.3.5
      - hotspotsc==1.0.0
      - psutil==7.2.2
      - ray==2.9.3
      - scikit-misc==0.5.2
      - scvi-tools==1.1.6.post2
      - symphonypy==0.2.0
      - harmonypy==0.0.10
      - triku==2.1.4
      - -e .[dev]
