name: stomics_visium_5samples_spatial_main_native_num_features_extra
output_dir: results/spatial_main_native_seed0_fix3/stomics_visium_5samples_spatial_main
datasets:
- configs/datasets/stomics_visium_5samples.yaml
feature_selection_methods:
- name: TFs
- name: random
- name: scanpy_seurat
- name: scanpy_seurat_batch
- name: scanpy_seurat_v3
- name: scanpy_seurat_v3_batch
- name: scanpy_cell_ranger
- name: scanpy_cell_ranger_batch
- name: scanpy_pearson
- name: scanpy_pearson_batch
- name: seurat_vst
- name: seurat_mvp
- name: seurat_disp
- name: seurat_sct
  params:
    max_cells: 3000
- name: scsegindex
- name: dubstepr
  params:
    max_cells: 5000
- name: nbumi
  params:
    max_cells: 5000
- name: osca
- name: scry
- name: singleCellHaystack
  params:
    max_cells: 5000
- name: Brennecke
- name: scPNMF
  params:
    max_cells: 3000
- name: triku
  params:
    max_cells: 5000
- name: hotspot
  params:
    max_cells: 3000
- name: anticor
  params:
    max_cells: 3000
- name: statistic_mean
- name: statistic_variance
- name: wilcoxon
integration_methods:
- name: scvi
  params:
    n_latent: 30
    max_epochs: 100
    batch_size: 2048
- name: cellcharter
  params:
    n_latent: 30
    nhood_layers: 4
    spatial_neighbors: 6
    max_epochs: 100
- name: gpsa
  params:
    n_input_dims: 20
    m_x_per_view: 50
    m_g: 50
    max_epochs: 200
    learning_rate: 0.01
    fixed_view_idx: 0
- name: staligner
  params:
    hidden_dims:
    - 128
    - 30
    n_epochs: 600
    lr: 0.001
    knn_neigh: 50
    radius_cutoff: 50.0
tasks:
- name: integration_eval
  params:
    n_neighbors: 15
- name: clustering_eval
  params:
    n_clusters: 15
    n_neighbors: 8
- name: alignment_eval
  params:
    n_neighbors: 10
    max_points_per_slice: 2500
n_features:
- 100
- 200
- 5000
- 10000
seeds:
- 0
save_embeddings: true
